// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Calculadora.UI.Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Metodo de teste da interface para operação de adição
        /// </summary>
        public void Test_UI_Adicao()
        {
            #region Variable Declarations
            WinEdit uINomeEdit = this.UIDebugWindow.UIItemWindow.UICalculadoraWinFormseListItem.UINomeEdit;
            WinButton uIFecharButton = this.UIDebugWindow.UIDebugTitleBar.UIFecharButton;
            WinComboBox uIAbrirComboBox = this.UIExecutarWindow.UIItemWindow.UIAbrirComboBox;
            WinEdit uIAbrirEdit = this.UIExecutarWindow.UIItemWindow1.UIAbrirEdit;
            WinButton uIMinimizarButton = this.UIDebugWindow.UIDebugTitleBar.UIMinimizarButton;
            WinClient uICalculadoraClient = this.UICalculadoraWindow.UICalculadoraClient;
            WinEdit uITxtPrimeiroNumeroEdit = this.UICalculadoraWindow.UITxtPrimeiroNumeroWindow.UITxtPrimeiroNumeroEdit;
            WinEdit uITxtSegundoNumeroEdit = this.UICalculadoraWindow.UITxtSegundoNumeroWindow.UITxtSegundoNumeroEdit;
            WinComboBox uICmbOperacaoComboBox = this.UICalculadoraWindow.UICmbOperacaoWindow.UICmbOperacaoComboBox;
            WinButton uICalcularButton = this.UICalculadoraWindow.UICalcularWindow.UICalcularButton;
            WinButton uIFecharButton1 = this.UICalculadoraWindow.UICalculadoraTitleBar.UIFecharButton;
            #endregion

            // Last mouse action was not recorded.

            // Click 'Nome' text box
            Mouse.Click(uINomeEdit, new Point(101, 12));

            // Click 'Fechar' button
            Mouse.Click(uIFecharButton, new Point(6, 17));

            // Press keyboard shortcut keys 'Windows + r'
            Keyboard.SendKeys(this.Test_UI_AdicaoParams.SendKeys, ModifierKeys.Windows);

            // Select 'D:\TreinaWeb\TreinaWeb.Calculadora\Calculadora.WinForms\bin\Debug' in 'Abrir:' combo box
            uIAbrirComboBox.EditableItem = this.Test_UI_AdicaoParams.UIAbrirComboBoxEditableItem;

            // Type '{Enter}' in 'Abrir:' text box
            Keyboard.SendKeys(uIAbrirEdit, this.Test_UI_AdicaoParams.UIAbrirEditSendKeys, ModifierKeys.None);

            // Double-Click 'Nome' text box
            Mouse.DoubleClick(uINomeEdit, new Point(82, 14));

            // Click 'Minimizar' button
            Mouse.Click(uIMinimizarButton, new Point(17, 8));

            // Click 'Calculadora' client
            Mouse.Click(uICalculadoraClient, new Point(145, 3));

            // Type '2' in 'txtPrimeiroNumero' text box
            uITxtPrimeiroNumeroEdit.Text = this.Test_UI_AdicaoParams.UITxtPrimeiroNumeroEditText;

            // Type '2' in 'txtSegundoNumero' text box
            uITxtSegundoNumeroEdit.Text = this.Test_UI_AdicaoParams.UITxtSegundoNumeroEditText;

            // Select 'Adição' in 'cmbOperacao' combo box
            uICmbOperacaoComboBox.SelectedItem = this.Test_UI_AdicaoParams.UICmbOperacaoComboBoxSelectedItem;

            // Click 'Calcular' button
            Mouse.Click(uICalcularButton, new Point(37, 11));

            // Click 'Fechar' button
            Mouse.Click(uIFecharButton1, new Point(26, 13));
        }
        
        #region Properties
        public virtual Test_UI_AdicaoParams Test_UI_AdicaoParams
        {
            get
            {
                if ((this.mTest_UI_AdicaoParams == null))
                {
                    this.mTest_UI_AdicaoParams = new Test_UI_AdicaoParams();
                }
                return this.mTest_UI_AdicaoParams;
            }
        }
        
        public UIDebugWindow UIDebugWindow
        {
            get
            {
                if ((this.mUIDebugWindow == null))
                {
                    this.mUIDebugWindow = new UIDebugWindow();
                }
                return this.mUIDebugWindow;
            }
        }
        
        public UIExecutarWindow UIExecutarWindow
        {
            get
            {
                if ((this.mUIExecutarWindow == null))
                {
                    this.mUIExecutarWindow = new UIExecutarWindow();
                }
                return this.mUIExecutarWindow;
            }
        }
        
        public UICalculadoraWindow UICalculadoraWindow
        {
            get
            {
                if ((this.mUICalculadoraWindow == null))
                {
                    this.mUICalculadoraWindow = new UICalculadoraWindow();
                }
                return this.mUICalculadoraWindow;
            }
        }
        #endregion
        
        #region Fields
        private Test_UI_AdicaoParams mTest_UI_AdicaoParams;
        
        private UIDebugWindow mUIDebugWindow;
        
        private UIExecutarWindow mUIExecutarWindow;
        
        private UICalculadoraWindow mUICalculadoraWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Test_UI_Adicao'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class Test_UI_AdicaoParams
    {
        
        #region Fields
        /// <summary>
        /// Press keyboard shortcut keys 'Windows + r'
        /// </summary>
        public string SendKeys = "r";
        
        /// <summary>
        /// Select 'D:\TreinaWeb\TreinaWeb.Calculadora\Calculadora.WinForms\bin\Debug' in 'Abrir:' combo box
        /// </summary>
        public string UIAbrirComboBoxEditableItem = "D:\\TreinaWeb\\TreinaWeb.Calculadora\\Calculadora.WinForms\\bin\\Debug";
        
        /// <summary>
        /// Type '{Enter}' in 'Abrir:' text box
        /// </summary>
        public string UIAbrirEditSendKeys = "{Enter}";
        
        /// <summary>
        /// Type '2' in 'txtPrimeiroNumero' text box
        /// </summary>
        public string UITxtPrimeiroNumeroEditText = "2";
        
        /// <summary>
        /// Type '2' in 'txtSegundoNumero' text box
        /// </summary>
        public string UITxtSegundoNumeroEditText = "2";
        
        /// <summary>
        /// Select 'Adição' in 'cmbOperacao' combo box
        /// </summary>
        public string UICmbOperacaoComboBoxSelectedItem = "Adição";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIDebugWindow : WinWindow
    {
        
        public UIDebugWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Debug";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIDebugTitleBar UIDebugTitleBar
        {
            get
            {
                if ((this.mUIDebugTitleBar == null))
                {
                    this.mUIDebugTitleBar = new UIDebugTitleBar(this);
                }
                return this.mUIDebugTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIDebugTitleBar mUIDebugTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Modo de Exibição de Itens";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UICalculadoraWinFormseListItem UICalculadoraWinFormseListItem
        {
            get
            {
                if ((this.mUICalculadoraWinFormseListItem == null))
                {
                    this.mUICalculadoraWinFormseListItem = new UICalculadoraWinFormseListItem(this);
                }
                return this.mUICalculadoraWinFormseListItem;
            }
        }
        #endregion
        
        #region Fields
        private UICalculadoraWinFormseListItem mUICalculadoraWinFormseListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UICalculadoraWinFormseListItem : WinListItem
    {
        
        public UICalculadoraWinFormseListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "Calculadora.WinForms.exe";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINomeEdit
        {
            get
            {
                if ((this.mUINomeEdit == null))
                {
                    this.mUINomeEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINomeEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Nome";
                    this.mUINomeEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINomeEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINomeEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIDebugTitleBar : WinTitleBar
    {
        
        public UIDebugTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinButton UIFecharButton
        {
            get
            {
                if ((this.mUIFecharButton == null))
                {
                    this.mUIFecharButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIFecharButton.SearchProperties[WinButton.PropertyNames.Name] = "Fechar";
                    this.mUIFecharButton.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUIFecharButton;
            }
        }
        
        public WinButton UIMinimizarButton
        {
            get
            {
                if ((this.mUIMinimizarButton == null))
                {
                    this.mUIMinimizarButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMinimizarButton.SearchProperties[WinButton.PropertyNames.Name] = "Minimizar";
                    this.mUIMinimizarButton.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUIMinimizarButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIFecharButton;
        
        private WinButton mUIMinimizarButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIExecutarWindow : WinWindow
    {
        
        public UIExecutarWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Executar";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Executar");
            #endregion
        }
        
        #region Properties
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow11 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow1 mUIItemWindow;
        
        private UIItemWindow11 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "12298";
            this.WindowTitles.Add("Executar");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIAbrirComboBox
        {
            get
            {
                if ((this.mUIAbrirComboBox == null))
                {
                    this.mUIAbrirComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIAbrirComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Abrir:";
                    this.mUIAbrirComboBox.WindowTitles.Add("Executar");
                    #endregion
                }
                return this.mUIAbrirComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIAbrirComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1001";
            this.WindowTitles.Add("Executar");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAbrirEdit
        {
            get
            {
                if ((this.mUIAbrirEdit == null))
                {
                    this.mUIAbrirEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAbrirEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Abrir:";
                    this.mUIAbrirEdit.WindowTitles.Add("Executar");
                    #endregion
                }
                return this.mUIAbrirEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAbrirEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UICalculadoraWindow : WinWindow
    {
        
        public UICalculadoraWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Calculadora";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Calculadora");
            #endregion
        }
        
        #region Properties
        public WinClient UICalculadoraClient
        {
            get
            {
                if ((this.mUICalculadoraClient == null))
                {
                    this.mUICalculadoraClient = new WinClient(this);
                    #region Search Criteria
                    this.mUICalculadoraClient.SearchProperties[WinControl.PropertyNames.Name] = "Calculadora";
                    this.mUICalculadoraClient.WindowTitles.Add("Calculadora");
                    #endregion
                }
                return this.mUICalculadoraClient;
            }
        }
        
        public UITxtPrimeiroNumeroWindow UITxtPrimeiroNumeroWindow
        {
            get
            {
                if ((this.mUITxtPrimeiroNumeroWindow == null))
                {
                    this.mUITxtPrimeiroNumeroWindow = new UITxtPrimeiroNumeroWindow(this);
                }
                return this.mUITxtPrimeiroNumeroWindow;
            }
        }
        
        public UITxtSegundoNumeroWindow UITxtSegundoNumeroWindow
        {
            get
            {
                if ((this.mUITxtSegundoNumeroWindow == null))
                {
                    this.mUITxtSegundoNumeroWindow = new UITxtSegundoNumeroWindow(this);
                }
                return this.mUITxtSegundoNumeroWindow;
            }
        }
        
        public UICmbOperacaoWindow UICmbOperacaoWindow
        {
            get
            {
                if ((this.mUICmbOperacaoWindow == null))
                {
                    this.mUICmbOperacaoWindow = new UICmbOperacaoWindow(this);
                }
                return this.mUICmbOperacaoWindow;
            }
        }
        
        public UICalcularWindow UICalcularWindow
        {
            get
            {
                if ((this.mUICalcularWindow == null))
                {
                    this.mUICalcularWindow = new UICalcularWindow(this);
                }
                return this.mUICalcularWindow;
            }
        }
        
        public UICalculadoraTitleBar UICalculadoraTitleBar
        {
            get
            {
                if ((this.mUICalculadoraTitleBar == null))
                {
                    this.mUICalculadoraTitleBar = new UICalculadoraTitleBar(this);
                }
                return this.mUICalculadoraTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUICalculadoraClient;
        
        private UITxtPrimeiroNumeroWindow mUITxtPrimeiroNumeroWindow;
        
        private UITxtSegundoNumeroWindow mUITxtSegundoNumeroWindow;
        
        private UICmbOperacaoWindow mUICmbOperacaoWindow;
        
        private UICalcularWindow mUICalcularWindow;
        
        private UICalculadoraTitleBar mUICalculadoraTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UITxtPrimeiroNumeroWindow : WinWindow
    {
        
        public UITxtPrimeiroNumeroWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtPrimeiroNumero";
            this.WindowTitles.Add("Calculadora");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtPrimeiroNumeroEdit
        {
            get
            {
                if ((this.mUITxtPrimeiroNumeroEdit == null))
                {
                    this.mUITxtPrimeiroNumeroEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtPrimeiroNumeroEdit.WindowTitles.Add("Calculadora");
                    #endregion
                }
                return this.mUITxtPrimeiroNumeroEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtPrimeiroNumeroEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UITxtSegundoNumeroWindow : WinWindow
    {
        
        public UITxtSegundoNumeroWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtSegundoNumero";
            this.WindowTitles.Add("Calculadora");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtSegundoNumeroEdit
        {
            get
            {
                if ((this.mUITxtSegundoNumeroEdit == null))
                {
                    this.mUITxtSegundoNumeroEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtSegundoNumeroEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Primeiro número:";
                    this.mUITxtSegundoNumeroEdit.WindowTitles.Add("Calculadora");
                    #endregion
                }
                return this.mUITxtSegundoNumeroEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtSegundoNumeroEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UICmbOperacaoWindow : WinWindow
    {
        
        public UICmbOperacaoWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cmbOperacao";
            this.WindowTitles.Add("Calculadora");
            #endregion
        }
        
        #region Properties
        public WinComboBox UICmbOperacaoComboBox
        {
            get
            {
                if ((this.mUICmbOperacaoComboBox == null))
                {
                    this.mUICmbOperacaoComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUICmbOperacaoComboBox.WindowTitles.Add("Calculadora");
                    #endregion
                }
                return this.mUICmbOperacaoComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUICmbOperacaoComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UICalcularWindow : WinWindow
    {
        
        public UICalcularWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnCalcular";
            this.WindowTitles.Add("Calculadora");
            #endregion
        }
        
        #region Properties
        public WinButton UICalcularButton
        {
            get
            {
                if ((this.mUICalcularButton == null))
                {
                    this.mUICalcularButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICalcularButton.SearchProperties[WinButton.PropertyNames.Name] = "Calcular";
                    this.mUICalcularButton.WindowTitles.Add("Calculadora");
                    #endregion
                }
                return this.mUICalcularButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICalcularButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UICalculadoraTitleBar : WinTitleBar
    {
        
        public UICalculadoraTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Calculadora");
            #endregion
        }
        
        #region Properties
        public WinButton UIFecharButton
        {
            get
            {
                if ((this.mUIFecharButton == null))
                {
                    this.mUIFecharButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIFecharButton.SearchProperties[WinButton.PropertyNames.Name] = "Fechar";
                    this.mUIFecharButton.WindowTitles.Add("Calculadora");
                    #endregion
                }
                return this.mUIFecharButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIFecharButton;
        #endregion
    }
}
